name: sub_gc
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.68
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcurand=10.3.7.68
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.3.3
  - prompt-toolkit=3.0.47
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.12.5
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.14
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dill==0.3.8
      - fonttools==4.53.1
      - fsspec==2024.9.0
      - grpcio==1.66.1
      - h5py==3.11.0
      - imageio==2.35.1
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - matplotlib==3.9.2
      - multiprocess==0.70.16
      - munkres==1.0.12
      - nltk==3.4.5
      - pathos==0.3.2
      - pox==0.3.4
      - ppft==1.7.6.8
      - protobuf==5.28.1
      - psutil==6.0.0
      - pycocotools==2.0.8
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - scikit-image==0.24.0
      - scipy==1.14.1
      - speaksee==0.0.1
      - stanfordcorenlp==3.9.1.1
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tifffile==2024.8.30
      - tqdm==4.66.5
      - werkzeug==3.0.4

